Error: 'utf-8' codec can't decode byte 0x9d in position 681: invalid start byte
If decoding fails and ignore_decoding_failures is set - then try again to decode with "ignore" setting